### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by crumbycrumbycrumby** [dreamnettech/dreamtime#102]
Installed 1.0.0 successfully, used it for a while, but every time I try to install 1.1.0 it says "Installation Aborted - Setup was not completed successfully" after selecting the directory. No additional information provided.

![image](https://user-images.githubusercontent.com/54255621/66012140-f13ad180-e493-11e9-8369-cda10c44ce66.png)

*Enviroment:*
 - Version: 1.1.0]
 - OS: Windows 10 1903

**Comment by kolessios** [comment]
Thank you for the report, it is the first time I see this problem. Have you tried selecting another installation directory? I have no idea what specific problem could be, only common things like the directory has write permissions, the installer does not have sufficient permissions or there is not enough space for installation.

**Comment by crumbycrumbycrumby** [comment]
Thanks for the reply. I have tried multiple directories, different drives, and running the installer as administrator. I have plenty of space too.

**Comment by slitkx** [comment]
Right now it happened to me too. Win10, 64bit, write permissions available.

**Comment by slitkx** [comment]
Installation works now. Yes, most probably resetting folder+registry permissions made a trick.
