### ISSUE TITLE
100% memory usage 

### ISSUE THREAD

**Issue by casper0078** [dreamnettech/dreamtime#103]
os: windows 8.1 
i had before problem at transformation i fixed it now i got problem when i use my cpu to transform the picture it takes like 30 secounds then on task manger i find the memory get raised till it read 99% then pc freeze so i power it to restart.

**Comment by kolessios** [comment]
How much RAM do you have in your system? Remember that DreamTime recommends a minimum of 8 GB, the program can use more than 4 GB of RAM during a transformation so you may simply need more RAM.

**Comment by nmnrna** [comment]
> os: windows 8.1
> i had before problem at transformation i fixed it now i got problem when i use my cpu to transform the picture it takes like 30 secounds then on task manger i find the memory get raised till it read 99% then pc freeze so i power it to restart.

Hey, can you please tell how did you fix it? Thanks.
