### ISSUE TITLE
Randomize with a certain range

### ISSUE THREAD

**Issue by mannyluu96** [dreamnettech/dreamtime#107]
Allow us to set a range for each preference and have DreamTime randomize the values within the range

**Comment by CremaLuca** [comment]
@kolessios has this been implemented in 1.3.0? Can't see it anywhere

**Comment by kolessios** [comment]
This feature is now available in [DreamTime v1.3.1](https://forum.dreamnet.tech/d/42-dreamtime-v1-3-1) 🎉
