### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gabi9898** [dreamnettech/dreamtime#108]
after installing it gives me the next error

when i double click the shortcut a javascript error pops up

https://imgur.com/a/ZxmSLgw
1.1,
win 10 1903
version 0.1.2 works

**Comment by gabi9898** [comment]
https://stackoverflow.com/questions/38458118/nodejs-error-spawn-c-windows-system32-cmd-exe-enoent

**Comment by kolessios** [comment]
I close this as it seems an isolated problem or related to the operating system.
