### ISSUE TITLE
Have trouble with installing the Media Feature Pack

### ISSUE THREAD

**Issue by godlikeanyone** [dreamnettech/dreamtime#109]
My current system is Windows 10 Home(1809). This is not a N version for Windows 10; however, it says I need to download the Media Feature Pack to meet all the requirements. I have tried to install the correct version. Microsoft says my system is not an N version so that it cannot be installed. I also tried to run DreamTime as admin but this did not work. I turned on the Windows Media Player inside the features of Windows.
![Error](https://user-images.githubusercontent.com/26649232/67348404-6707f980-f577-11e9-8145-55215bc7c2cf.png)

**Comment by kolessios** [comment]
I close this since that requirement has been removed in v1.1.0, if you still have that problem please update to the latest version.
