### ISSUE TITLE
Stuck on white circle

### ISSUE THREAD

**Issue by trueman1996** [dreamnettech/dreamtime#123]
**Describe the bug**
I successfully opened the program once, I then downloaded the Dreampower resources through the program. Ever since I have been getting this white circle on a black screen. Deleted all files and started from scratch, same issue. Looking for some insight, thanks

![Capture](https://user-images.githubusercontent.com/58187167/69584285-34f11980-0fb3-11ea-9330-acd3b805a814.JPG)

Environment
 - Version 1.1.2
 - OS: Windows 7 64-Bit

**Comment by kolessios** [comment]
This can happen if the installed version of DreamPower is very old or corrupt. A quick solution is opening `%appdata%` (WIN + R) and deleting the folder called `dreamtime`.
