### ISSUE TITLE
Forum Confirmation Email Doesn't Arrive

### ISSUE THREAD

**Issue by k128** [dreamnettech/dreamtime#124]
I signed up for the forum with an email @Email.com and the confirmation email never arrived.  I've resent it multiple times on separate days and have checked my spam.  No email is coming through.

**Comment by kolessios** [comment]
Fuck. That explains some things. Thank you very much for letting me know, I have already fixed it.

**Comment by k128** [comment]
Had to click resend again but it works now.  Thanks!  If you can trigger a resend to everyone who hasn't confirmed, that might help them since they otherwise may not know that it's fixed.
