### ISSUE TITLE
After updating can not process png and jpeg like I was before and can't go back either

### ISSUE THREAD

**Issue by sashacw** [dreamnettech/dreamtime#125]
**Describe the bug**
  Error: usage: dreampower [-h] [-d] [-v] {run,checkpoints,gpu-info,daemon} ...
dreampower: error: Input C:\Users\Game\Pictures/madi_1.PNG file not supported format.

usage: dreampower [-h] [-d] [-v] {run,checkpoints,gpu-info,daemon} ... dreampower: error: Input C:\Users\Game\Pictures/madi_1.PNG file not supported format.

**To Reproduce**
1. Open program
2. Hit update
3. Try to run a picture

**Expected behavior**
For files to get converted like in the previous versions
**Screenshots**

**Enviroment (please complete the following information):**
 - Version [e.g. v1.1.2]
 - OS: [e.g. Windows 7]
 - Report URL: [If applicable, e.g. https://rollbar.com/occurrence/...]

**Additional context**

**Comment by kolessios** [comment]
It is a problem with DreamPower, it does not accept photos that have the extension in capital letters. Change the name of the photo from `madi_1.PNG` to `madi_1.png`

This problem will be fixed in the next version of DreamPower.

**Comment by themrpurple** [comment]
I have the same error @sashacw

**Comment by sashacw** [comment]
@kolessios 
This fix worked for some files but for the rest I get a different error.

The process has been interrupted by an unknown error, this may be caused by a corrupt installation, please check the console for more information.

For more information please take a screenshot and report the following on Github or here:

        Error: [INFO] Welcome to DreamPower
[INFO] GAN Processing Will Use CPU

[INFO] Executing Image Processing [INFO] Processing on C:\Users\Game\Pictures\madi/madi23.png

[INFO] Executing Image To Crop

[INFO] Executing Image To Resized Traceback (most recent call last): File "main.py", line 82, in <module> File "argv_init__.py", line 35, in run File "main.py", line 25, in main File "processing_init__.py", line 23, in run File "processing\image.py", line 78, in _execute

File "processing\worker.py", line 49, in runworker File "transform_init.py", line 26, in run File "processing__init.py", line 23, in run File "transform\opencv\resize.py", line 76, in execute File "transform\opencv\resize.py", line 83, in calculatenewsize ZeroDivisionError: float division by zero [3904] Failed to execute script main

[INFO] Welcome to DreamPower [INFO] GAN Processing Will Use CPU

[INFO] Executing Image Processing

[INFO] Processing on C:\Users\Game\Pictures\madi/madi23.png

[INFO] Executing Image To Crop [INFO] Executing Image To Resized Traceback (most recent call last): File "main.py", line 82, in <module> File "argv_init__.py", line 35, in run File "main.py", line 25, in main File "processing_init.py", line 23, in run File "processing\image.py", line 78, in execute File "processing\worker.py", line 49, in runworker File "transform__init.py", line 26, in run File "processing_init__.py", line 23, in run File "transform\opencv\resize.py", line 76, in execute File "transform\opencv\resize.py", line 83, in calculatenew_size ZeroDivisionError: float division by zero [8776] Failed to execute script main
