### ISSUE TITLE
Stuck on loading white circle

### ISSUE THREAD

**Issue by calvzzz** [dreamnettech/dreamtime#127]
Im a mac user once update screen is stuck on loading screen, uninstalled and installed again but wont work. Any solutions thanks!

**Comment by kolessios** [comment]
We need a little more information to solve the problem, DreamTime version and Windows version please.

**Comment by calvzzz** [comment]
Dreamtime version v1.1.2, mac platform

**Comment by calvzzz** [comment]
Please guide me on steps to fix this bug if the app works correctly im very happy to donate 

Thanks!

**Comment by kolessios** [comment]
Sorry to make you wait, sometimes we are busy. In 1.1.2 there is a bug in which if DreamTime detects that DreamPower has been installed but it is not accessible then it stays in that "frozen" state. To fix it you can go to `%appdata%/dreamtime` (WIN + R) and delete the `settings.json` file, if that doesn't work then delete the entire folder.
