### ISSUE TITLE
Run 1 has failed

### ISSUE THREAD

**Issue by bigrig112** [dreamnettech/dreamtime#131]
when i go to run a photo through dreampower it gives me this error:
Run 1 has failed
DreamPower has been interrupted by an unknown error, this may be caused by a corrupt installation, please check the console for more information.

I have tried reinstalling the program but it didnt fix the issue

**Comment by kolessios** [comment]
Please provide more information: DreamTime version, Windows version, text in the console of the failed photo.

**Comment by bigrig112** [comment]
im running windows 10 home os build 17763.864 version im running is 1.2.0 for dreamtime and im not sure how to access the console for dreamtime?

**Comment by bigrig112** [comment]
problem solved, did not realize png wasnt supported

**Comment by kolessios** [comment]
png is supported, in that case it is very likely that your photo ends in `.PNG`, rename it to `.png`
