### ISSUE TITLE
Human Interaction to the image

### ISSUE THREAD

**Issue by lmao123354324** [dreamnettech/dreamtime#133]
Hey guys, I love the app however I have noticed some other application like deepnude (only some versions) have the option to highlight where the body part is so it can be more accurate in creating the nude as simply sometimes the app just does not know what is going on and breaks. Thanks.

**Comment by kolessios** [comment]
I guess you mean painting the body layers (green, red, white, etc)

This feature will be available in v1.3.0

**Comment by thvozdovic** [comment]
> I guess you mean painting the body layers (green, red, white, etc)
> 
> This feature will be available in v1.3.0

How to use it ? Is it just matter of painting with random color ? Because theres nothing about it in the manual

**Comment by kolessios** [comment]
I will update the [guide](https://time.dreamnet.tech/docs/guide/upload) with information on how to use this feature as soon as possible (possibly between today and tomorrow).

I close because this request has already been implemented.
