### ISSUE TITLE
Installation Aborted

### ISSUE THREAD

**Issue by k128** [dreamnettech/dreamtime#134]
In control panel, it showed two versions of DreamTime installed (1.2.1 and 1.1.0).  I uninstalled the older one.  When I noticed that it was deleting all of my files from the DreamTime temp folder I force quit it to save what hadn't been deleted yet.  Now trying to uninstall either version gives me the message that the uninstall exe can't be found and trying to reinstall hangs with the loading bar at about 40% and the status reading "Installation Aborted.  Setup was not completed successfully."

Version: 1.2.1
OS: Windows 10

**Comment by kolessios** [comment]
I am sorry that you have those problems, for now we do not know why the installation is interrupted when an earlier version is installed, it only happens in specific scenarios. Clearly, it would be normal for the installation to update the application without problems.

For now, the only thing I can recommend is that you remove any trace of DreamTime and restart your computer before reinstalling. The two main folders are:

- The installation folder (the one you selected when installing the application for the first time).
- `%appdata%/dreamtime`

However, other users have reported that deleting these two folders is not enough and they have resorted to cleaning programs.

**Comment by k128** [comment]
I removed those folders and restarted.  It still won't install.  What cleaning programs have worked for other users?  Alternatively, if there was a way to get a copy of the uninstall exe I could try running that again, now that I have backed up what was left of my work.  

My guess is that the uninstallation program removes some other traces of DreamTime that are recognized by the installer (ie. registry).  The installer says that I have DreamTime installed and already knows the path that I had it installed in,  even though that path is gone now.  As for why it fails, I'd guess that it is expecting some file or folder to still exist that doesn't anymore, though obviously you'd have a better idea than me what it's doing.  

In addition to the reinstallation issue (which is my main concern at the moment), it would probably be good for DreamTime to not continue to show an older version in the Apps and Programs control panel window, since that is misleading and it might be good to provide an option to delete or leave the uncategorized models on uninstallation.

**Comment by kolessios** [comment]
One user reported success using [Bulk Crap Uninstaller](https://www.bcuninstaller.com/). As for the suggestions with the installation, we will take them into account however the installation is automatically generated by another program so we do not have enough control over it.

**Comment by k128** [comment]
Thanks!  I was able to get it reinstalled by using Bulk Crap Uninstaller to remove it and the registry items.  It somehow still said I already had an installation and knew the location, so I obviously missed something but this time it correctly reinstalled.
