### ISSUE TITLE
freezing while doing a transformation

### ISSUE THREAD

**Issue by jgmb-png** [dreamnettech/dreamtime#135]
im guessing this is memory related because i only have 4gb of ram but the program freezes after like 40 sec of tranformation. any way i can solve this or is it just pc related since of the below requirement ram (srry for the dumb question new here)

**Comment by kolessios** [comment]
Yes, the requirements we ask are the minimum to work without problems. We cannot help those with less resources beyond telling them to close all possible programs and try again.
