### ISSUE TITLE
Unexpected error!

### ISSUE THREAD

**Issue by mentalbacon** [dreamnettech/dreamtime#136]
Whetever i go to "nudify" i have this error

The application has encountered an unexpected error:
Cannot read property 'uploadMode' of undefined

**Comment by kolessios** [comment]
Please open `%appdata%/dreamtime` (WIN + R) and delete the `settings.json` file.

**Comment by kolessios** [comment]
Fixed in v1.2.2:
https://github.com/dreamnettech/dreamtime/releases/tag/v1.2.2
