### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by xhamsterlolman** [dreamnettech/dreamtime#140]
Run 1 has failed.
You have run out of VRAM on your GPU! Try a photo of smaller size or free all possible GPU use.
OK

this is shown after i updated from 1.1. any ideas?

**Comment by kolessios** [comment]
DreamTime should have forced you to update DreamPower and in the latest versions of the latter, VRAM consumption increased.  So you have 3 options:

- Stay on DreamTime v1.1 and don't update. (But we cannot support you if something fails)
- Use CPU processing.
- Buy a GPU with more memory.

**Comment by chris1122** [comment]
do u think that the consumption dicrease?
