### ISSUE TITLE
Run has failed

### ISSUE THREAD

**Issue by chris1122** [dreamnettech/dreamtime#141]
I know the consumption increased but i have a very good pc and still crashing, will this consume decrease with newest versions?

**Comment by kolessios** [comment]
When opening an Issue you must provide more information:

1. What is the error message? (A screenshot would help)
2. What version of DreamTime you are using.
3. What are the specifications of your system. (RAM, VRAM, Graphics card, CPU)

And probably in later versions the consumption of RAM and VRAM only grows.

**Comment by chris1122** [comment]
1     Run 1 has failed
      You have run out of VRAM on your GPU! Try a photo of smaller size or free all possible GPU use.
2    1.3.0
3    8 gb ram   3 gb vran  gtx1060  Ryzen 3 2200 3.5 ghz
![Captura](https://user-images.githubusercontent.com/53844238/71458909-c696a700-276a-11ea-99c3-9e7124f8affe.PNG)

Thats sad;(  i cant used anymore;(((

**Comment by kolessios** [comment]
Sorry, but GPUs with less than 6 GB of VRAM have had problems with the latest versions of DreamPower. The only things I can recommend is to close all possible programs that are using your GPU or use CPU processing.

**Comment by chris1122** [comment]
When i use CPU my pc crashes hahah;(

**Comment by DeepnudeEntusiast** [comment]
> Sorry, but GPUs with less than 6 GB of VRAM have had problems with the latest versions of DreamPower. The only things I can recommend is to close all possible programs that are using your GPU or use CPU processing.

Not in my case i have less than 2GB and run perfectky

**Comment by DeepnudeEntusiast** [comment]
> Sorry, but GPUs with less than 6 GB of VRAM have had problems with the latest versions of DreamPower. The only things I can recommend is to close all possible programs that are using your GPU or use CPU processing.

That's why i use CPU before GPU because i have 8GB RAM and 2 USB of 4GB each used like RAM so in total i have 15.85GB to run  Dreamtime and works perfect without any issue
