### ISSUE TITLE
Download Links Broken

### ISSUE THREAD

**Issue by portalrule123** [dreamnettech/dreamtime#145]
Attempting to download from github (for Windows version at least) produces the following error:

ipfs resolve -r /ipns/QmUvudWPzRa7hgDSVFiwzFzviAZJohTrvHJNhnvytuPv3H/Releases/DreamTime/v1.3.0/DreamTime-v1.3.0-windows.exe: no link named "v1.3.0" under QmQawArdMHEzoZGLpZiGLd9RJEkFFE9Tt74TVxHdsQpTbS

**Comment by kolessios** [comment]
Sorry for the interruption! The links should work now 🙂
