### ISSUE TITLE
For everyone facing uploadMode or app not found on preferences

### ISSUE THREAD

**Issue by enzp** [dreamnettech/dreamtime#146]
For everyone facing uploadMode or app not found on preferences or settings (I don't remember the exact error message), I just deleted the settings.json file (I don't remember where it was stored, but you can find it with a file search on your OS finder) that should force the app to re-create it and that will add the missing config settings that leads to the bug, it is a missmatch between what the system expects to find on the settings file through versions

**Comment by enzp** [comment]
I think a good solution to this would be to load the new config as something like 
```javascript
const loadedConfig = {
  ...defaultConfig,
  ...configLoadedFromDisk,
}
```

**Comment by kolessios** [comment]
Thanks for the information but this system is only for reporting Issues not solutions, in addition the solution to this problem is already available at: https://github.com/dreamnettech/dreamtime#common-problems

**Comment by enzp** [comment]
sorry about that, I swear it was only on with the hope of helping anothers :)
