### ISSUE TITLE
Not really a new feature request

### ISSUE THREAD

**Issue by ColoradoExpertta** [dreamnettech/dreamtime#148]
Congrats on this version.
I still find that I have the best results using the manual cropping option.
Please never eliminate that feature.

Thanks again

**Comment by kolessios** [comment]
Thank you! Clearly that is a very popular option and the only thing we will do is improve it. I also remind you that thanks and comments are best written in our [Discord or forum](https://time.dreamnet.tech/docs/support/feedback). 😁
