### ISSUE TITLE
Editor, cropping and/or resizing functionality.

### ISSUE THREAD

**Issue by b00sher** [dreamnettech/dreamtime#158]
Hi, it will be useful to have an ability to scale/resize/select needed part of image in the editor. I don't see how adding text on image or drawing geometrical shapes might be useful and how the feature of this importance is missing. 

Update: I found out that it is possible to change detection to manual and _then_ there will be a menu to crop the image. Still, it would be great and more obvious if something like that could be done in the editor. Or consider to show a tip when a user enters the editor.

Update: I read the [manual](https://time.dreamnet.tech/docs/guide/photo-panel#crop), sorry for bothering. At this point, the main objective of the issue is to move cropping functionality to the editor tab. But since it has the needed functionality, it might as well count as a suggestion, rather than an issue. 

Thanks anyway!

**Comment by kolessios** [comment]
Thank you very much for the feedback, in this case both the Editor and the Cropper are external libraries of which I don't have much control.  The editor has a built-in Cropper but not in the proper way for this work (1:1 - 512x512) so it is disabled and the Crop of the tab must be used.

For now I think we will use the tutorial system to indicate that the Crop is in a different place.

**Comment by kolessios** [comment]
🎉 "Tutorial" added in v1.4.2
