### ISSUE TITLE
Cant run, superbug multiple instance creation on startup

### ISSUE THREAD

**Issue by harsh1412** [dreamnettech/dreamtime#162]
![Capture](https://user-images.githubusercontent.com/20555951/72700650-7694df80-3b72-11ea-9de5-70fb4ffe3e25.JPG)
This happens when i try to run it.
This is my first installation.
I tried portable and older version too but no result.
My os win 10
allowed firewall manually.
also tried disabling firewall but same bug.
It also multiple its instances after i click on OK msg popup for some reason.

**Comment by kolessios** [comment]
I am very sorry that you have this problem. DreamTime must have a stable connection to Github at the time of starting to be able to download the missing components, in this case it was not possible to establish such a connection and therefore a restart loop was made.

Please make sure DreamTime has access to the Internet and that you can access these links:

- https://api.github.com/repos/dreamnettech/dreampower/releases
- https://api.github.com/repos/dreamnettech/dreampower-checkpoints/releases

**Comment by kolessios** [comment]
🎉 The restart loop has been fixed in v1.4.2, I hope that the other problem in your case was due to your Internet connection.
