### ISSUE TITLE
areola nipple back to 0.0

### ISSUE THREAD

**Issue by xhamsterlolman** [dreamnettech/dreamtime#164]
hallo,I wanted to make a suggestion. Since version 3.5 or something you have made it mandatory that there is a fake areola and nipple on all results. The minimum is 0,3 that we can choose.before that with a preference of 0.0 there were a lot of cases when the model was close enough where we could achieve a transparency effect with 0.0 you could make out exactly where and how big the areola was. if you tinker a little with the result with a third party program like gimp you could achieve excellent results.now with the fake nipple it is unesthaitic and confusing.I think the program has lost since the mandatory insertion of 0.3 and I don't understand the reason for this rule anyway.

Please restore the option of 0.0 on nipple and areola thank you very much for your excellent work!!

**Comment by kolessios** [comment]
Interestingly, it was never intentional to allow the nipple/aeorola option to have a minimum of 0, it was actually a bug, but with what you say I can see why you want it restored.

Thank you for your report, it will be restored in the next version:

![](https://www.fulcrumgallery.com/product-images/P934770-10/its-not-a-bug-its-a-feature-black-background.jpg)

**Comment by xhamsterlolman** [comment]
thank you for your answer and for your willingness to restore it.since we are talking,may i ask sthg?in regard to the size of boobs am i correct in assuming that a value of 1 is the actual boob size of the model? anything less is smaller than the truth,anything more,higher than 1,is bigger ? i am interested in accurate as possible results,that is why I ask the question.keep up the excellent work!

**Comment by kolessios** [comment]
I contacted @deeppppp  (algorithm developer) to confirm what I believed.

Short answer:
Yes. 1.0 represents leaving the value exactly as the AI has believed it is the size of the woman's boobs. A multiplication

@deeppppp answer:
The algo comes up with an ellipse shape with a certain properties (see `cv2.ellipse()` draw function)
it has a center coord, then a tuple for the major and minor axes length
the input from the user multiplies the minor/major axis length value.
So if the algo thinks the ellipse should be a circle of 50px radius (minor/major axis length 50)
and the user gave the value of 0 then the ellipse would not be drawn.
The 1.0 keeps the algo results the same. but for each image these results can have different values for the ellipse min/maj axis length.
it's not an absolute size for the ellipse. but a multiplier x the algo results.
