### ISSUE TITLE
Nudification failed!  

### ISSUE THREAD

**Issue by Gorreado** [dreamnettech/dreamtime#165]
Nudification failed!
There was a problem saving the nudified photo. Please make sure you have enough disk space and the folders in Settings do not have special characters or spaces.

----------------------------------------------------------------------------------------------
Error: [DEBUG] C:\Users\XXXX\AppData\Roaming\dreamtime\dreampower\checkpoints

[DEBUG] {'correct_to_mask': 'C:\\Users\\XXXX\\AppData\\Roaming\\dreamtime\\dreampower\\checkpoints\\cm.lib', 'maskref_to_maskdet': 'C:\\Users\\XXXX\\AppData\\Roaming\\dreamtime\\dreampower\\checkpoints\\mm.lib', 'maskfin_to_nude': 'C:\\Users\\XXXX\\AppData\\Roaming\\dreamtime\\dreampower\\checkpoints\\mn.lib', 'checkpoints_path': 'C:\\Users\\Julian\\AppData\\Roaming\\dreamtime\\dreampower\\checkpoints'}

[DEBUG] 
Namespace(altered=None, asize=1, auto_rescale=True, auto_resize=False, auto_resize_crop=False, bsize=1, checkpoints={'correct_to_mask': 'C:\\Users\\XXXX\\AppData\\Roaming\\dreamtime\\dreampower\\checkpoints\\cm.lib', 'maskref_to_maskdet': 'C:\\Users\\XXXX\\AppData\\Roaming\\dreamtime\\dreampower\\checkpoints\\mm.lib', 'maskfin_to_nude': 'C:\\Users\\XXXX\\AppData\\Roaming\\dreamtime\\dreampower\\checkpoints\\mn.lib', 'checkpoints_path': 'C:\\Users\\XXXX\\AppData\\Roaming\\dreamtime\\dreampower\\checkpoints'}, color_transfer=False, cpu=True, debug=True, disable_persistent_gan=False, export_step=None, export_step_path=None, func=<function main at 0x00000297A38348B8>, gpu=None, gpu_ids=None, hsize=0, ignore_size=False, input='D:/User/XXXX/Descargas/Shareit/Mi A1/photo/51424867_2253847434830421_3183178830625898496_o_1.jpg', json_args=None, json_folder_name='settings.json', mode='run', n_cores=4, n_runs=1, nsize=1, output='D:\\User\\XXXX\\Im�genes\\DreamTime\\Uncategorized\\51424867-22538474348-RUN1-1581841969238-dreamtime.jpg', overlay=None, prefs={'titsize': 1, 'aursize': 1, 'nipsize': 1, 'vagsize': 1, 'hairsize': 0}, steps=(5, 6), vsize=1)
[INFO] Welcome to DreamPower
[INFO]
 GAN Processing Will Use CPU

[DEBUG] Process to execute : <processing.image.ImageProcessing object at 0x00000297A3867D88>

[INFO] Executing Image Processing

[DEBUG] All Phases : [<class 'transform.opencv.resize.ImageToRescale'>, <class 'transform.opencv.correct.DressToCorrect'>, <class 'transform.gan.mask.CorrectToMask'>, <class 'transform.opencv.mask.MaskToMaskref'>, <class 'transform.gan.mask.MaskrefToMaskdet'>, <class 'transform.opencv.mask.MaskdetToMaskfin'>, <class 'transform.gan.mask.MaskfinToNude'>]
[DEBUG] To Be Executed Phases : [<class 'transform.gan.mask.MaskfinToNude'>]

[INFO] Processing on ['D:/User/XXXX/Descargas/Shareit/Mi A1/photo/51424867_2253847434830421_3183178830625898496_o_1.jpg', 'D:/User/XXXX/Descargas/Shareit/Mi A1/photo/51424867_2253847434830421_3183178830625898496_o_1.jpg', 'D:/User/XXXX/Descargas/Shareit/Mi A1/photo/51424867_2253847434830421_3183178830625898496_o_1.jpg', 'D:/User/XXXX/Descargas/Shareit/Mi A1/photo/51424867_2253847434830421_3183178830625898496_o_1.jpg', 'D:/User/XXXX/Descargas/Shareit/Mi A1/photo/51424867_2253847434830421_3183178830625898496_o_1.jpg', 'D:/User/XXXX/Descargas/Shareit/Mi A1/photo/51424867_2253847434830421_3183178830625898496_o_1.jpg', 'D:/User/XXXX/Descargas/Shareit/Mi A1/photo/51424867_2253847434830421_3183178830625898496_o_1.jpg']

[DEBUG] wk []
[DEBUG]
 Loading Model Start
[INFO] Loading GAN Model For maskfin_to_nude

[DEBUG] Model load done in 2.98 seconds

[INFO] Executing Maskfin To Nude
[DEBUG] GAN Processing will use CPU

[DEBUG] Maskfin To Nude Done in 16.75 seconds

[ERROR] 
Something gone wrong writing D:\User\XXXX\Im�genes\DreamTime\Uncategorized\51424867-22538474348-RUN1-1581841969238-dreamtime.jpg image file. The final result is not a valid image file.

    at fe.getPowerError (file:///C:/Users/XXXX/AppData/Local/Programs/DreamTime/resources/app.asar/dist/_nuxt/fc8b3f3018b0816f4cf4.js:1:24281)
    at file:///C:/Users/XXXX/AppData/Local/Programs/DreamTime/resources/app.asar/dist/_nuxt/fc8b3f3018b0816f4cf4.js:1:23555
    at CallbacksRegistry.apply (electron/js2c/renderer_init.js:1804:29)
    at electron/js2c/renderer_init.js:1603:21
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:1593:7)
    at EventEmitter.emit (events.js:203:13)
    at Object.onMessage (electron/js2c/renderer_init.js:2399:16)

------------------------------------------------------------------------------------------------------------

It is my first time with the program, I have not completed even once satisfactorily
Could you help me? eh tried changing the folders and reinstalling the program
my disk drive is 1tb, half of it is occupied

 - DreamTime Version [1.4.2]
 - OS: [ Windows 10 ]
 - RAM: [ 16 GB]
 - GPU: [GTX 1060 3 GB VRAM]
 - CPU:  i3 8100 

I will try to communicate, I'm sorry if my English is bad I speak Spanish

**Comment by kolessios** [comment]
Thanks for your report, it seems that because your operating system is in Spanish the folder where the photos are stored is set to `D:\User\XXXX\Imágenes\DreamTime`.  This is a problem since the nudification will fail if the folder has accents or special characters (Imágenes). Please change the folder in `Settings -> Folders`.

**Comment by Gorreado** [comment]
Woah, thanks! It has worked!
I congratulate you for the prompt response, I hope you keep updating
I never imagined that could be the mistake

**Comment by kolessios** [comment]
Thanks to you! In the next version we will place alerts with this information. 😊
