### ISSUE TITLE
Question: why is the repository hidden from not logged in users?

### ISSUE THREAD

**Issue by b00sher** [dreamnettech/dreamtime#168]
Hi, a while ago, I wrote this to Github support (partially shown):

> I was trying to see this https://github.com/dreamnettech/dreamtime repository, but a login prompt showed out. It was available after authorization though. What is the reason for that? Why can I git-clone it without being logged in, but can't see it using web version?
> 
> To reproduce:
> Open an incognito window/clean cookies, than go to https://github.com/dreamnettech/dreamtime.

And after roughly a month, I got a response from Mitch (partially shown):

>  In order to protect the privacy and security of our users, we do not share specific details related to settings or configurations on accounts or repositories that you do not own.

I didn't find an option to hide a repo from not logged in users, did you set things like that? 
If yes, how and why? 
If no, were you aware of this, why is it this way?

**Comment by kolessios** [comment]
Like you, we do not have an option to limit visibility only to users who have logged in. In my opinion it seems that the person who answered you has believed that our repository is private. (a feature when paying a Github subscription, a subscription that **we do not have**)

![](https://i.gyazo.com/c11ad9794d818e4a8001ad1fd75aed24.png)

We believe that repositories of this type (adult content) that gain some popularity are hidden behind the "login wall", but that's a reestriccion imposed by Github and we can do nothing to remove it.

In the end it really doesn't affect us much, we have the [official website](https://time.dreamnet.tech) to offer the releases and an account is needed anyway to report suggestions or issues.

To see the source code without a Github account you can access any of the links offered in the "DreamNet" section of DreamTime:

- [DreamNet Git](https://git.dreamnet.tech/dreamnet/dreamtime)
- [Codeberg](https://codeberg.org/dreamnet/dreamtime)
- [GitGud](https://gitgud.io/dreamnet/dreamtime)
- [Antopie](https://code.antopie.org/dreamnet/dreamtime)
- [Teknik](https://git.teknik.io/dreamnet/dreamtime)
- [Spip](https://git.spip.net/kolessios/dreamtime)

**Comment by b00sher** [comment]
Yes, it was probably a misunderstanding. I don't know anyone with private repos to test whether they show login prompt or just return 404/403, but it seems to affect only repositories with adult content (first three search result for "deepnude"): [1](https://github.com/stacklikemind/deepnude_official), [2](https://github.com/zhengyima/DeepNude_NoWatermark_withModel), [3](https://github.com/Hengle/DeepNewdsForAndroid).
My intention was to ask why do they do this. Now you have confirmed that it wasn't your will, so I can write-back and further clarify the ticket. Thanks!
