### ISSUE TITLE
Boobs scale to zero

### ISSUE THREAD

**Issue by xhamsterlolman** [dreamnettech/dreamtime#170]
Hallo I had asked at earlier time to reduce nipples and areolas to 0.

Is it possible to do the same thing with the boobs size category. The minimum is 0.3 and sometimes it gets in the way. Thank you very much.

**Comment by kolessios** [comment]
🎉 Added to DreamTime v1.4.5

**Comment by xhamsterlolman** [comment]
happy to hear from you,hope all of you are staying safe and untouched by the pandemic

Αποκτήστε το Outlook για Android<https://aka.ms/ghei36>

________________________________
