### ISSUE TITLE
Dreamtime freezes up whole PC in middle of the transformation.

### ISSUE THREAD

**Issue by TheStar01** [dreamnettech/dreamtime#172]
**Describe the bug**
It freezes the computer during transformation and I can't even move the mouse so I have to shut down manually from the box.

**Enviroment:**
 - DreamTime Version: v1.4.4 (latest)
 - OS: Windows 10 Pro
 - RAM: 8 GB
 - GPU: AMD Radeon RX 570 8 GB GDDR5

**Additional context**
Thanks :)

**Comment by ryurazu** [comment]
Using up all is ram, sometimes peak usage will take even the reversed ram
and can cause crashes. Wish there was an option to limit the ram usage.

**Comment by xrebel1** [comment]
Install 16GB+ RAM

**Comment by Hacedion777** [comment]
run as exclusive app closing down all other RAM hogs before transformation to avoid crash

**Comment by TheStar01** [comment]
> run as exclusive app closing down all other RAM hogs before transformation to avoid crash

Thank you, but how do I do that? :)

**Comment by Hacedion777** [comment]
close everything you're not using, every single non-essential program even you antivirus temporarily if you have too...

**Comment by kolessios** [comment]
Although we recommend at least 8 GB of RAM, some users like you have reported similar problems, but it all comes down to the same thing: **The algorithm consumes all the available RAM**. For now there is not much that can be done but:

- As @Hacedion777 has said, close all possible programs on your computer and let DreamTime be the only one.
- Try smaller photos.
- Buy more RAM.

**Comment by TheStar01** [comment]
OK, thank you to everyone for your effort :)
