### ISSUE TITLE
Code 403

### ISSUE THREAD

**Issue by Juanpaaab** [dreamnettech/dreamtime#173]
So this happen after I clicked install. Any idea what happen? 
![IMG_20200416_234832](https://user-images.githubusercontent.com/23732627/79533146-d2211d00-803c-11ea-8abd-14b18728fec5.jpg)

**Comment by anonboiyo** [comment]
bump, got the same error

**Comment by kolessios** [comment]
Sorry for the problem. This should be fixed now and the new download system will prevent this from happening again. Open DreamTime again and try it. 🙂
