### ISSUE TITLE
Can there be a trade off of power for time?

### ISSUE THREAD

**Issue by BisPa** [dreamnettech/dreamtime#177]
**Describe**
I am thinking that for people as me (With low resources computing power) it would be neat if instead of the program crashing because our computers can't handle it, maybe it can nudify our pictures but with the exchange that obviously it will take a lot longer. 

**Describe alternatives you've considered**
Or also there can be an option inside of the program where the menu also uses less resources (It would look uglier and all of that but it would be a fair trade).

**Additional context**
To be honest, I don't know much about coding and computing stuff, so please don't judge me too hard :). Any clarification is appreciated.

**Comment by kolessios** [comment]
Thanks for your feedback, however the resource management of the algorithm that is causing the crash is out of our control. A new algorithm is being developed that could consume less resources (but nothing big). The requirements will continue to be more than 8 GB of RAM or VRAM. Sorry 😓
