### ISSUE TITLE
Waifu2X update error

### ISSUE THREAD

**Issue by asjdf** [dreamnettech/dreamtime#182]
**Describe the bug**
when i want to update the Waifu2X

Could not call remote method 'getPath'. Check that the method signature is correct. Underlying error: The "path" argument must be of type string. Received type object Underlying stack: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object at validateString (internal/validators.js:112:11) at join (path.js:375:7) at Object.getPath (B:\Users\At\Desktop\DreamTime-v1.5.4-windows-portable\resources\app.asar\electron\dist\modules\tools\paths.js:6:55) at electron/js2c/browser_init.js:233:7775 at IpcMainImpl. (electron/js2c/browser_init.js:233:4236) at IpcMainImpl.emit (events.js:223:5) at WebContents. (electron/js2c/browser_init.js:173:8647) at WebContents.emit (events.js:223:5)

**Enviroment (please complete the following information):**
 - DreamTime Version 1.5.4 
 - OS: Windows 10 1903
 - RAM: 16G

**Comment by kolessios** [comment]
DreamTime v1.5.5 has been released and includes a section with detailed information about the problem that prevents the download, please install this new version and open a new issue with the information that appears there. Thanks!
