### ISSUE TITLE
Unable to update to dreamtime v1.6.2 MacOS

### ISSUE THREAD

**Issue by kidcharlemange** [dreamnettech/dreamtime#222]
**Describe the bug**
Currently running v1.6.0 and have tried to update to v1.6.1 and v1.6.2. 
However when trying to start the application, get an error message saying "Dreamtime failed to start: Cannot read property 'advanced' of undefined <code>Cannot read property 'advanced of undefined</code>"

**To Reproduce**
1. Download and install v1.6.1 or v1.6.2
2. Go to applications folder
3. Click on 'Dreamtime'

**Expected behavior**
Dreamtime application to start normally. Last version that works consistently is v1.6.0.

**Screenshots**
<img width="415" alt="Screenshot 2021-03-18 at 2 39 20 PM" src="https://user-images.githubusercontent.com/80878709/112109204-3bfe5b00-8bec-11eb-9835-c09ae19d169d.png">

**Enviroment (please complete the following information):**
 - DreamTime Version [1.6.1 & 1.6.2]
 - OS: [macOs Catalina 10.15.7]
 - RAM: [4 GB]
 - CPU: [2.4Ghz Dual-Core Intel Core i5]
 - GPU: [Intel Iris]

**Comment by ladiesman0305** [comment]
Same issue here. 1.6.0 works fine until 1.6.1 and 1.6.2.

**Environment:**

DreamTime Version [1.6.1 & 1.6.2]
OS: [macOs Big Sur 11.2.3]
RAM: [16 GB]
CPU: [Apple Silicon M1]
GPU: [M1]

**Comment by kolessios** [comment]
Fixed in [v1.5.3](https://github.com/dreamnettech/dreamtime/releases/tag/v1.6.3) 🥳
