### ISSUE TITLE
Helping AI

### ISSUE THREAD

**Issue by barbarosp** [dreamnettech/dreamtime#78]
It could help AI if app would offer templates to put on boobs. Such as a bikini or a bra. You would resize and position it accordingly. Therefore app wouldn't put awkward boobs on weird spots in not so naked or angled pictures. It would even be better if we could use this templates in 3d then would get reasonable results in angled pictures if the subject is angled on Z axis.

**Comment by kolessios** [comment]
Thanks for the feedback. This has been partially implemented with advanced custom masks mode in DreamTime v1.5
