### ISSUE TITLE
Please create AUR package

### ISSUE THREAD

**Issue by sTiKyt** [dreamnettech/dreamtime#87]
**Is your feature request related to a problem? Please describe.**
It takes little action to install DreamTime on ArchLinux when you have to unpack .deb and put folders manually.

**Describe the solution you'd like**
It would be great to install it using AUR.
**Describe alternatives you've considered**
Also there is BlackArch repository, you can add it without any problems, just make request.

**Comment by PommeDroid** [comment]
I have already created a package for Dreampower (cli) on the AUR. It was planned that I package also Dreamtime, but at the moment it requires 777 permission.  ->
https://github.com/private-dreamnet/dreamtime/blob/84edd71cf4c33d31a45e2c7c4b1816bbd643e73d/src/electron/modules/settings.js#L136

And I am not packaging something with a 777 permission requirement. So, a patch is required before I can package it on the AUR. I plan to provide it, but I can't tell when it will be available.

**Comment by kolessios** [comment]
I suppose this problem is due to the fact that the configuration file is saved in the same directory as the program, which causes 777 permissions to be required. I will fix this for 1.2

**Comment by PommeDroid** [comment]
If we want to fix this correctly I thinks that we need to do 2 things : 
* set the settings.json in the data user directory by default or if the root is not writeable 
* do the same for  the checkpoints or make possible to select the path by the user (note that I added the -c,  --checkpoints  option on the cli that make this possible )

**Comment by AlfioSaitta** [comment]
I created a rudimentary version of the package, but only for CPU processing (my video card does not support cuda 10, only cuda 9.1 not compatible with pytorch which requires at least cuda 9.2).

Easy to install with the command:
`pacman -U dreamtime-1.1.0-1-x86_64.pkg.tar.xz`

As soon as i can, i upload it somewhere
![immagine](https://user-images.githubusercontent.com/10280718/68506866-d3b70f80-026a-11ea-99ff-8924711dc32b.png)

![immagine](https://user-images.githubusercontent.com/10280718/68506977-137df700-026b-11ea-90fb-d92a3ababa1c.png)

**Comment by kolessios** [comment]
I am not an Linux expert but for version 1.1.3 we will try to change from .deb to snap, I understand that with Snap it will be easy to install it on most linux-based operating systems.

**Comment by sTiKyt** [comment]
@kolessios isn't snap slower and downloads and not space efficient?

**Comment by kolessios** [comment]
> @kolessios isn't snap slower and downloads all libraries for each install (not space efficient)?

To be honest I don't know but it is the easiest way for me to distribute the app right now. btw, I'm a magician of fast answers, I know.

**Comment by kolessios** [comment]
Although it is not exactly what is requested in this issue... since version 1.5.7 the application is officially in the [Snap Store](https://snapcraft.io/dreamtimetech) which makes it relatively easy to install it in almost any distribution with a single command.

Therefore I will close this issue but feel free to open another if you think that the Snap Store has more disadvantages than advantages.

**Comment by sTiKyt** [comment]
> Although it is not exactly what is requested in this issue... since version 1.5.7 the application is officially in the [Snap Store](https://snapcraft.io/dreamtimetech) which makes it relatively easy to install it in almost any distribution with a single command.
> 
> Therefore I will close this issue but feel free to open another if you think that the Snap Store has more disadvantages than advantages.

Arch Linux community prefers to use AUR instead of snap due to snap being messy and performance/space inefficient, but whatever, if it's on snap - someone will make AUR package sooner or later
