### ISSUE TITLE
Image quallity

### ISSUE THREAD

**Issue by k1klop** [dreamnettech/dreamtime#95]
Love the software but the only problem i have with it is the poor end result image quallity compared to Deepnudes the filesize is only 30% Of the size of deepnudes and its much blurrier. Is there a way to fix this?

**Comment by janakptl00** [comment]
Agree with K1klop that we need higher quality or higher pixel range function.

**Comment by chip83** [comment]
yes, image quality is very poor. The resolution is low and the compression is too strong.
Is not possible to implement an option for select the resolution and the compression ratio (using the JPG format?)

**Comment by kolessios** [comment]
🎉 This has been fixed in v1.1.2:
https://github.com/dreamnettech/dreamtime/releases/tag/v1.1.2
